/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package com.averity.simple.warehouse

import org.springframework.boot.SpringApplication
import org.springframework.boot.autoconfigure.SpringBootApplication

@SpringBootApplication
class SimpleWarehouse {

    static void main(String[] args) {
        SpringApplication.run(SimpleWarehouse, args)
    }
}
